modLoader="javafml"
loaderVersion="[47,)"
license="Apache 2.0"
showAsResourcePack=false

[[mods]]
  modId="jukeboxmutes"
  version="beta-0.0"
  displayName="Jukebox Mutes Music (Official Author's Version)"
  authors="MsDogGirl, and not some pig who's stolen it."
  description='''
  When a music disc plays, mutes the game music. Fixes music overlap issue.
  '''

